'use client';
import {useEffect,useRef,useState} from 'react';
import {gsap} from 'gsap';
import {DEFAULT_CENTER,type Point,type Spot} from '@/lib/model';
import type * as Leaflet from 'leaflet';

export type MapControl={pan:(p:Point)=>void;zoom:(n:number)=>void;center:()=>Point;fit:(points:Point[])=>void;search:(q:string)=>Promise<{name:string;address:string;lat:number;lng:number}[]>};
type Props={spots:Spot[];kakaoKey?:string;selected?:string;draftRoute:Point[];navigationPath?:Point[];currentLocation?:Point;numbered?:boolean;onSelect:(s:Spot)=>void;onPick:(p:Point)=>void;onReady:(c:MapControl)=>void;onProvider:(p:string)=>void};
declare global{interface Window{kakao:any;}}
let kakaoPromise:Promise<void>|null=null;
function loadKakao(key:string){if(window.kakao?.maps?.Map)return Promise.resolve();if(kakaoPromise)return kakaoPromise;kakaoPromise=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');const timer=setTimeout(()=>reject(new Error('지도 연결 대기')),7000);script.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${encodeURIComponent(key)}&autoload=false&libraries=services,clusterer`;script.onload=()=>{if(!window.kakao?.maps?.load){clearTimeout(timer);reject(new Error('지도 사용 설정 확인'));return;}window.kakao.maps.load(()=>{clearTimeout(timer);resolve();});};script.onerror=()=>{clearTimeout(timer);reject(new Error('지도 연결 대기'));};document.head.appendChild(script);});return kakaoPromise;}
function pin(s:Spot,onClick:()=>void){const el=document.createElement('button');el.type='button';el.className='photo-pin'+(s.ar?' ar-pin':'');el.setAttribute('aria-label',s.title+' 골목 기록 보기');if(s.image){const img=document.createElement('img');img.src=s.image;img.alt='';img.draggable=false;const frame=document.createElement('span');frame.className='pin-media';frame.appendChild(img);el.appendChild(frame);}else{const text=document.createElement('span');text.className='pin-note';text.textContent=s.body.slice(0,22);el.appendChild(text);}if(s.ar){const tag=document.createElement('span');tag.className='pin-tag';tag.textContent='AR';el.appendChild(tag);}const label=document.createElement('span');label.className='pin-label';label.textContent=s.title;el.appendChild(label);el.onclick=e=>{e.stopPropagation();onClick();};return el;}

export default function MapCanvas(props:Props){const host=useRef<HTMLDivElement>(null);const current=useRef(props);current.current=props;const mapRef=useRef<any>(null);const mode=useRef('');const library=useRef<typeof Leaflet|null>(null);const overlays=useRef<any[]>([]);const [revision,setRevision]=useState(0);const revealed=useRef(new Set<string>());
 useEffect(()=>{let disposed=false;let observer:ResizeObserver|undefined;let local:any=null;
  const setUp=async()=>{let useKakao=false;if(props.kakaoKey){try{await loadKakao(props.kakaoKey);useKakao=true;}catch{useKakao=false;}}if(disposed||!host.current)return;
   if(useKakao){const k=window.kakao.maps;local=new k.Map(host.current,{center:new k.LatLng(DEFAULT_CENTER.lat,DEFAULT_CENTER.lng),level:6});mode.current='kakao';mapRef.current=local;k.event.addListener(local,'click',(e:any)=>current.current.onPick({lat:e.latLng.getLat(),lng:e.latLng.getLng()}));k.event.addListener(local,'zoom_changed',()=>setRevision(v=>v+1));
    current.current.onReady({pan:p=>local.panTo(new k.LatLng(p.lat,p.lng)),zoom:n=>local.setLevel(local.getLevel()-n),center:()=>({lat:local.getCenter().getLat(),lng:local.getCenter().getLng()}),fit:points=>{if(!points.length)return;const bounds=new k.LatLngBounds();points.forEach(p=>bounds.extend(new k.LatLng(p.lat,p.lng)));local.setBounds(bounds,55,45,55,45);},search:q=>new Promise(resolve=>new k.services.Places().keywordSearch(q,(data:any[],status:string)=>resolve(status===k.services.Status.OK?data.slice(0,6).map(v=>({name:v.place_name,address:v.road_address_name||v.address_name,lat:Number(v.y),lng:Number(v.x)})):[])))});
    observer=new ResizeObserver(()=>local.relayout());current.current.onProvider('kakao');
   }else{const L=await import('leaflet');if(disposed||!host.current)return;library.current=L;local=L.map(host.current,{zoomControl:false,attributionControl:true}).setView([DEFAULT_CENTER.lat,DEFAULT_CENTER.lng],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a>'}).addTo(local);mode.current='osm';mapRef.current=local;local.on('click',(e:Leaflet.LeafletMouseEvent)=>current.current.onPick({lat:e.latlng.lat,lng:e.latlng.lng}));local.on('zoomend',()=>setRevision(v=>v+1));
    current.current.onReady({pan:p=>local.flyTo([p.lat,p.lng],Math.max(local.getZoom(),15),{duration:.6}),zoom:n=>local.setZoom(local.getZoom()+n),center:()=>({lat:local.getCenter().lat,lng:local.getCenter().lng}),fit:points=>{if(points.length)local.fitBounds(points.map(p=>[p.lat,p.lng]),{padding:[45,55],maxZoom:17});},search:async()=>[]});observer=new ResizeObserver(()=>local.invalidateSize());current.current.onProvider('osm');
   }if(disposed)return;observer?.observe(host.current);setRevision(v=>v+1);
  };setUp().catch(()=>current.current.onProvider('error'));
  return()=>{disposed=true;observer?.disconnect();overlays.current.forEach(o=>{if(o.setMap)o.setMap(null);else o.remove?.();});overlays.current=[];if(mode.current==='osm')local?.remove();mapRef.current=null;if(host.current)host.current.replaceChildren();};
 },[props.kakaoKey]);
 useEffect(()=>{const m=mapRef.current;if(!m)return;overlays.current.forEach(o=>{if(o.setMap)o.setMap(null);else o.remove?.();});overlays.current=[];const L=library.current;const k=window.kakao?.maps;const compact=window.matchMedia('(max-width:760px)').matches;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const tweens:gsap.core.Tween[]=[];let revealIndex=0;const zoom=mode.current==='osm'?m.getZoom():20-m.getLevel();const groups=new Map<string,Spot[]>();const cell=props.numbered?0:zoom<13?.025:zoom<15?.003:0;
  props.spots.forEach(s=>{const key=cell?`${Math.floor(s.lat/cell)}:${Math.floor(s.lng/cell)}`:s.id;groups.set(key,[...(groups.get(key)||[]),s]);});
  groups.forEach(group=>{const s=group[0];let el:HTMLButtonElement;if(group.length>1){el=document.createElement('button');el.className='cluster-pin';el.textContent=String(group.length);el.setAttribute('aria-label',`${group.length}개 골목 흔적 확대`);el.onclick=e=>{e.stopPropagation();current.current.onReady;mode.current==='osm'?m.setView([s.lat,s.lng],m.getZoom()+2):m.setLevel(Math.max(1,m.getLevel()-2),{anchor:new k.LatLng(s.lat,s.lng)});};}else{el=pin(s,()=>current.current.onSelect(s));if(s.id===props.selected)el.classList.add('selected');if(props.numbered){el.querySelector('.pin-tag')?.remove();const tag=document.createElement('span');tag.className='pin-tag pin-waypoint';tag.textContent=String(props.spots.findIndex(p=>p.id===s.id)+1);el.appendChild(tag);}}
   if(mode.current==='kakao'){const overlay=new k.CustomOverlay({position:new k.LatLng(s.lat,s.lng),content:el,yAnchor:1,zIndex:s.id===props.selected?20:5});overlay.setMap(m);overlays.current.push(overlay);}else if(L){const marker=L.marker([s.lat,s.lng],{icon:L.divIcon({html:el,className:'map-photo-marker',iconSize:props.numbered?[54,61]:group.length>1?(compact?[44,44]:[50,50]):(compact?[68,77]:[82,91]),iconAnchor:props.numbered?[27,68]:group.length>1?(compact?[22,22]:[25,25]):(compact?[34,85]:[41,99])}),zIndexOffset:s.id===props.selected?1000:0}).addTo(m);overlays.current.push(marker);}
   const revealKey=group.map(spot=>spot.id).join(',');if(!reduced&&!revealed.current.has(revealKey)){revealed.current.add(revealKey);tweens.push(gsap.fromTo(el,{y:14,scale:.85,opacity:0},{y:0,scale:1,opacity:1,duration:.65,delay:Math.min(revealIndex++*.055,.35),ease:'back.out(1.4)',clearProps:'transform,opacity'}));}
  });const path=props.navigationPath??(props.draftRoute.length?props.draftRoute:props.spots.find(s=>s.id===props.selected)?.route||[]);
  if(props.currentLocation){const p=props.currentLocation;if(mode.current==='kakao'){const dot=document.createElement('span');dot.className='location-pin';dot.setAttribute('aria-label','내 위치');const overlay=new k.CustomOverlay({position:new k.LatLng(p.lat,p.lng),content:dot,zIndex:30});overlay.setMap(m);overlays.current.push(overlay);}else if(L)overlays.current.push(L.circleMarker([p.lat,p.lng],{radius:8,color:'#fff',weight:3,fillColor:'#348cc0',fillOpacity:1}).addTo(m));}
  if(path.length){if(mode.current==='kakao'){const line=new k.Polyline({path:path.map(p=>new k.LatLng(p.lat,p.lng)),strokeWeight:5,strokeColor:'#BC7116',strokeOpacity:.9});line.setMap(m);overlays.current.push(line);}else if(L){overlays.current.push(L.polyline(path.map(p=>[p.lat,p.lng] as [number,number]),{color:'#BC7116',weight:5}).addTo(m));}}
  return()=>tweens.forEach(tween=>tween.kill());
 },[props.spots,props.selected,props.draftRoute,props.navigationPath,props.currentLocation,props.numbered,revision]);
 return <div ref={host} className="map-canvas" aria-label="기웃 골목 지도"/>;
}
